# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.1.0
_src_path: https://github.com/napari/napari-plugin-template
display_name: Animation Timeline
email: brisvag@gmail.com
full_name: Lorenzo Gaifas
github_repository_url: https://github.com/brisvag/napari-animation-timeline
github_username_or_organization: brisvag
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: false
include_writer_plugin: false
install_dependabot: true
install_precommit: true
license: BSD-3
module_name: napari_animation_timeline
plugin_name: napari-animation-timeline
short_description: A plugin to make napari animations using a detailed timeline with
    keyframes.
